### ISSUE TITLE
ctrl+b to build doesn't work

### ISSUE THREAD

**Issue by kevinresol** [jeremyfa/language-haxe#3]
I am not sure why it is related to this package because i suppose ctrl+b build is provided by the atom-haxe package. But yes the hotkey does not work when I am using this package. (the original language-haxe is fine though)

**Comment by kevinresol** [comment]
Hm... this is strange. I went to the setting pages of atom-haxe and found that the build trigger is bound to .haxe and .hxml files. I added .hx and then it worked again. So the question here is why .haxe not .hx and why the original language-haxe worked?

**Comment by jeremyfa** [comment]
atom-haxe used .haxe because the original language-haxe was using .haxe as well.

But, instead, it should be .hx (just have to look at other packages to see the pattern: javascript -> .js / typescript -> .ts etc...).

This language-haxe fork is fixed regarding this problem but atom-haxe doesn't handle the change yet. However we can make atom-haxe work with both "extensions" easily, I will push a change on atom-haxe for that, as it won't affect users of original language-haxe anyway :) (and it will allow the original package to be fixed as well, without breaking atom-haxe)

**Comment by jeremyfa** [comment]
Should be fixed in atom-haxe v0.8.14 (https://github.com/snowkit/atom-haxe/commit/82062e1ecd491fe3b5666f5d4f26a646ee67ff5d)
